### ISSUE TITLE
Discussão sobre base de dados

### ISSUE THREAD

**Issue by biliboss** [NewSchoolBR/newschool-backend#5]
Fala galera, resolvi criar essa issue para discutirmos o armazenamento de dados. 

Vamos de Relacional ou NoSQL?

Eu geralmente uso Postgres para tudo, nunca tive problemas e eu ainda consigo armazenar "documentos" se necessário. 

Fechando esse assunto, eu posso me responsabilizar em subir um Vagrant ou Docker para termos a base localmente para todos os devs.

**Comment by DavideCarvalho** [comment]
Estou implementando a parte de segurança e comecei a fazer a conexão com MySql (já que tinha sido falado no grupo pra usarmos), porém o driver de mysql do node não consegue fazer a conexão com o MySql mais novo por causa do esquema de segurança, tendo que mudar configuração no banco de dados pra isso.

Achei minha trabalhoso pra um projeto open source, então acho válido pensarmos em outras opções.

**Comment by DavideCarvalho** [comment]
Considerando que vai tudo estar no mesmo projeto, ou seja, vai ser um microservição (pelo menos nesse primeiro momento), deveríamos ir de algo mais certo e sólido, como SQL

**Comment by biliboss** [comment]
@DavideCarvalho está acostumado trabalhar com base local? Docker ou Vagrant? 

PS: eu vi os branches depois de ter postado a issue 🤦‍♂😆

**Comment by DavideCarvalho** [comment]
To sim, tava até pensando em criar um docker-compose pra subir a aplicação com o banco de dados até

**Comment by raffacabofrio** [comment]
Já discutimos isso senhores. Vamos de MySQL.

- grande suporte de comunidade.
- mais fácil e barato de conseguir hospedagem.
- fácil de gerenciar.

Mas se liguem que não temos apego a tecnologia. Mais pra frente e gente pode mudar de opinião. blz?
