### ISSUE TITLE
Problema endpoint PUT /Lesson

### ISSUE THREAD

**Issue by ViniciusDalmazzo** [NewSchoolBR/newschool-backend#83]
Conforme analisado na imagem a API está retornando sucesso ao enviar um PUT de Lesson porém eu alterei a descrição da aula e ela me retornou a descrição antiga, não alterando as informações.

![error_put_lesson](https://user-images.githubusercontent.com/30936204/72522931-81333a00-383d-11ea-8f36-a8f76deffa11.jpg)

**Comment by ericguim** [comment]
checking

**Comment by ericguim** [comment]
#107

**Comment by ericguim** [comment]
solved
