### ISSUE TITLE
404 ao buscar curso por slug

### ISSUE THREAD

**Issue by andrews-felipe** [NewSchoolBR/newschool-backend#84]
Requisição
![image](https://user-images.githubusercontent.com/26348646/72561322-b82e3d80-3887-11ea-81c4-4a8ea4cfea44.png)

Resposta

![image](https://user-images.githubusercontent.com/26348646/72561678-79e54e00-3888-11ea-8078-32f86adef98b.png)

Banco
![image](https://user-images.githubusercontent.com/26348646/72561344-c419ff80-3887-11ea-853b-4242aa07517f.png)

**Comment by DavideCarvalho** [comment]
Testei algumas vezes aqui e o slug sempre era criado corretamente e conseguia achar, consegue dar detalhes de como esse curso foi criado pra esse slug estar errado?

**Comment by DavideCarvalho** [comment]
Tenta criar um curso de novo e tentar procurar por ele. Se continuar com erro, pode abrir de novo
