### ISSUE TITLE
Verificar se o curso já foi iniciado pelo usuário

### ISSUE THREAD

**Issue by andrews-felipe** [NewSchoolBR/newschool-backend#86]
A tela do curso na visão do aluno é essa

![image](https://user-images.githubusercontent.com/26348646/72566616-ed8c5880-3892-11ea-9118-363c7beb943d.png)

porém precisamos de alguma forma verificar se o curso já está em andamento, então podemos criar um endpoint pra fazer essa verificação, antes do carregamento da tela, assim eu faria um UI dinâmica pra ele ter a opção de `continuar`

**Comment by DavideCarvalho** [comment]
O Eric criou um endpoint que retorna o curso iniciado pelo aluno, ta na PR dele

**Comment by DavideCarvalho** [comment]
Fechando
