### ISSUE TITLE
Resposta incompleta para listagem aulas

### ISSUE THREAD

**Issue by andrews-felipe** [NewSchoolBR/newschool-backend#88]
Na tela de listagem de aulas a seguir
![image](https://user-images.githubusercontent.com/26348646/72582025-255dc500-38c0-11ea-88c5-be968ade2bd4.png)
podemos ver que ela apresenta o nome do curso com a descrição(ao invez da descrição poderia vir o nome do author mesmo) nesse caso também é preciso uma flag concluido por enquanto, pra o front poder mostrar as aulas já concluídas.

resposta atual

![image](https://user-images.githubusercontent.com/26348646/72582170-a74dee00-38c0-11ea-9b69-81fb1e1e1b2c.png)

**Comment by ericguim** [comment]
Conforme conversamos, esse cara não é uma issue, o front está requisitando do endpoint errado.
