### ISSUE TITLE
Erro na url no retorno do e-mail de recuperar senha

### ISSUE THREAD

**Issue by filipefelice** [NewSchoolBR/newschool-backend#91]
E-mail chega corretamente, porém a url está como undefined.
http://undefined/undefined?changePasswordRequestId=65b17cda-6df7-4896-9775-c3040aea8624

![WhatsApp Image 2020-01-16 at 14 55 33](https://user-images.githubusercontent.com/36074458/72670314-f0b25080-3a1a-11ea-925b-71884c74977a.jpeg)

**Comment by DavideCarvalho** [comment]
Fechando issue
