### ISSUE TITLE
Criação do campo de enunciado para Teste

### ISSUE THREAD

**Issue by rafaelvnunes** [NewSchoolBR/newschool-backend#94]
Atualmente o usuário não sabe qual o enunciado do teste que ele precisa responder, se deixarmos o título da questão como enunciado vai dar problemas de overflow e complicador para questões longas, como problemas de matemática, interpretação e história, por exemplo.

**Comment by ericguim** [comment]
#103

**Comment by ericguim** [comment]
Resolved
